services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_REF:-devashishbelwal/authtodo:latest}
    container_name: authtodo_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
