secrets:
  mongodb_uri:
    file: .env

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - mongodb_uri
    container_name: authtodo_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
